from typing import Any, List, Iterable, Union


class DataKeeper:
    root_dir: str
    DataDir: str
    __entries: List

    def __init__(self) -> None: ...

    def UpdateEntries(self, **kwargs: Iterable) -> None: ...

    def GetLastEntry(self) -> Any: ...

    def GetAllEntries(self) -> Any: ...

    def RmEntriesByKeys(self, *args: Iterable) -> None: ...

    def GetEntryByKey(self, key: Union[int, str]) -> Any: ...

    def GetAvailableKeys(self) -> List: ...

    def AddEntries(self, **kwargs: Iterable) -> None: ...