from typing import List, Any, Iterable


class InputModel:
    iEntries: List
    def __init__(self) -> None: ...

    def __str__(self) -> str: ...

    @staticmethod
    def ParseEntry(entry: Any) -> Any: ...

    def AddNewEntries(self, entries: Iterable) -> None: ...

    def AddNewEntry(self, entry: Any) -> None: ...
